### ISSUE TITLE
Does not list databases from a named instance

### ISSUE THREAD

**Issue by withanhdammit** [martin9700/New-SQLBackupReport#2]
One of my SQL servers has a default instance plus a named instance.  The databases from the default instance are all listed correctly, none of the databases on the named instance are listed.

**Comment by martin9700** [comment]
Have to hunt down a SQL server with a named instance, but in the mean time can you tell me how you're specifying the instance?  Text file, directly to the Name parameter?

It _should_ be in servername\instancename format.

**Comment by withanhdammit** [comment]
That's how I tried it but it said it couldn't ping the server.

**Comment by martin9700** [comment]
Just committed a fix for this problem.  Can you please test it and let me know?  Thanks.

**Comment by withanhdammit** [comment]
That fixed it!  Thanks for this, it's a very cool script!
